### ISSUE TITLE
Internet Explorer 11 not displaying due to React 16 upgrade in apiconnect-explorer

### ISSUE THREAD

**Issue by amargreen** [ibm-apiconnect/devportal-addons#8] opened 2019-07-22 18:41 UTC
Definitions are not rendered in Internet Explorer. Browser shows an error: 
Unable to generate example data. The error reported was : '[object ErrorEvent]'

Is this module not supported on Internet Explorer? There are some online references to ReactJS having troubles with IE. Is it the same case with this functionality?

Thanks,
amar

**Comment by chrisdudley** [comment] 2019-07-22 19:14
What version of IE?
Can you post a screenshot?
Or the api you used to produce the issue?

We need some info to reproduce the problem please

**Comment by chrisdudley** [comment] 2019-07-22 21:06
Oh and what version of explorer please?

**Comment by amargreen** [comment] 2019-07-23 14:26
I am using Internet Explorer 11.
Attached is the sample yaml I got it from internet and deployed for verification.
[telecon-1.0.0.zip](https://github.com/ibm-apiconnect/devportal-addons/files/3422541/telecon-1.0.0.zip)

**Comment by redlanne** [comment] 2019-07-23 14:46
what version of apiconnect-explorer are you using?

**Comment by amargreen** [comment] 2019-07-23 14:53
Pasting information from apiexplorer.info. 
name = API Explorer
description = Use API Explorer to render APIs
package = "IBM API Connect"
core = 7.x
dependencies[] = api

version = 1.0

**Comment by chrisdudley** [comment] 2019-07-23 14:55
Thats the module info - we need the version of the npm apiconnect-explorer package you downloaded please

**Comment by amargreen** [comment] 2019-07-23 15:04
Is this is the correct path? apiexplorer\explorer\app\version.json:
{
	"version" : {
		"name":      "apiconnect-explorer",
		"buildDate": "Mon Apr 15 2019 19:18:56 GMT+0100 (British Summer Time)",
		"version":   "4.1.64"
	}
}

If this is not the correct path, please guide me where to find the information

**Comment by redlanne** [comment] 2019-07-23 16:04
that version is very old (latest version is 4.1.105)

I cannot reproduce with latest version - please upgrade and if you are still seeing the error then reopen the issue.  The browser is likely a red herring as a lot of issues of this nature have since been fixed.

**Comment by amargreen** [comment] 2019-07-23 18:20
I have installed 4.1.105. I ran into different issue with Internet Explorer now. API page is blank.
Chrome and Firefox are working fine though.
Please find attached screen.
![APIExplorer_IE](https://user-images.githubusercontent.com/43353282/61736840-f8878580-ad54-11e9-85ac-2a2398193b7e.jpg)

**Comment by redlanne** [comment] 2019-07-24 08:54
hmmm Jacqs took a look at this rendered in the v2018 portal via IE (though 
I had a similar issue on my IE install on my windows server)

Anne Redwood
IBM API Connect Development
IBM United Kingdom Limited
Hursley, Winchester, UK
+44 (0) 1962 816840
anne.redwood@uk.ibm.com

**Comment by redlanne** [comment] 2019-07-24 08:54
Bah!(assuming Jacqs checked the wrong browser)  Since upgraded a whole 
heap of things including going from React 15 to React 16.  So I am able to 
recreate on my remote box.  I think I need to add some polyfills.  Will 
look tomorrow or Thursday (though more inclined to prioritise Deutsche 
Bahn as that is expected in an APAR).

Anne Redwood
IBM API Connect Development
IBM United Kingdom Limited
Hursley, Winchester, UK
+44 (0) 1962 816840
anne.redwood@uk.ibm.com





From:   Anne Redwood/UK/IBM
To:     ibm-apiconnect/devportal-addons 
<reply@reply.github.com>
Date:   23/07/2019 22:59
Subject:        Re: [ibm-apiconnect/devportal-addons] Internet Explorer 
display issues (#8)


hmmm Jacqs took a look at this rendered in the v2018 portal via IE (though 
I had a similar issue on my IE install on my windows server)

Anne Redwood
IBM API Connect Development
IBM United Kingdom Limited
Hursley, Winchester, UK
+44 (0) 1962 816840
anne.redwood@uk.ibm.com

**Comment by chrisdudley** [comment] 2019-07-24 09:54
Reopening as this looks like a genuine IE11 issue

**Comment by redlanne** [comment] 2019-07-24 09:57
The earlier build was still React 15 and had some generator bugs, which are now fixed.  Unfortunately the latest version includes upgrades to React 16, which does genuinely break IE11 - will get the work arounds included and a new explorer published.

**Comment by amargreen** [comment] 2019-07-24 13:18
could you suggest an earlier version I can use until issues with latest version are fixed?

**Comment by redlanne** [comment] 2019-07-24 13:34
4.1.76 - would be my best guess

**Comment by chrisdudley** [comment] 2020-08-28 15:28
Internet Explorer has now been killed off by microsoft so i am closing this.

**Closed by chrisdudley** 2020-08-28 15:28 UTC
